### ISSUE TITLE
Nested comments don't display

### ISSUE THREAD

**Issue by emma-borhanian** [emma-borhanian/arbital-scrape#1]
Pages don't display nested comments.

**Comment by shreyanshrs44** [comment]
Hi, I would like to work on this issue. Can you help to get started ?

**Comment by emma-borhanian** [comment]
e.g. this page:
https://emma-borhanian.github.io/arbital-scrape/page/consciousness_research_time_sensitive.html
should include this nested comment:
https://emma-borhanian.github.io/arbital-scrape/page/6xh.html

You can run `npm install && ./arbital-scrape.js` and see these HTML files in the `out/` directory.
Comments are displayed here:
https://github.com/emma-borhanian/arbital-scrape/blob/master/template/page.pug#L41
`comment.commentIds` has the nested comments.
You can display them nested recursively using a pug mixin (mixin=function): https://pugjs.org/language/mixins.html

**Comment by shreyanshrs44** [comment]
Thanks for the references. Running `./arbital-scope.js` takes lot of time more than 30 minutes and still running. How long it takes for you ?

**Comment by emma-borhanian** [comment]
It should be producing output to stdout rapidly. If it's not something's wrong. Try `node arbital-scrape.js` instead. I had to do that in continuous integration for some reason or it would hang. I'm not sure why the shebang isn't working.

**Comment by emma-borhanian** [comment]
It takes <5 minutes for me.

**Comment by shreyanshrs44** [comment]
`node arbital-scrape.js` worked for a while, then it crashed because of out of heap memory.

**Comment by shreyanshrs44** [comment]
Terminal output :
`
writing tmp/mathjax-2.7.5.zip
extracting tmp/mathjax-2.7.5.zip to out

<--- Last few GCs --->

[7050:0x3aba9f0]   493963 ms: Mark-sweep 1389.9 (1434.3) -> 1389.5 (1436.3) MB, 2521.5 / 0.0 ms  (average mu = 0.075, current mu = 0.005) allocation failure scavenge might not succeed
[7050:0x3aba9f0]   496284 ms: Mark-sweep 1391.8 (1436.3) -> 1391.5 (1438.3) MB, 2305.0 / 0.0 ms  (average mu = 0.043, current mu = 0.007) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x28ff43f5be1d]
Security context: 0x14c50e71e6e9 <JSObject>
    1: new /* anonymous */ [0xdf2ac4f9449] [/home/shreyansh/Documents/Github/arbital-scrape/node_modules/adm-zip/headers/entryHeader.js:~5] [pc=0x28ff443b3c40](this=0x2f4ecf9610c9 <JSObject>)
    2: ConstructFrame [pc: 0x28ff43f0d02f]
    3: new /* anonymous */ [0xdf2ac4fb071] [/home/shreyansh/Documents/Github/arbital-scrape/node_modules/adm-zip/zipEntry.js:...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8f9d10 node::Abort() [node]
 2: 0x8f9d5c  [node]
 3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4152  [node]
 6: 0xef4258 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00332 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf00c64 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf038d1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xeccd54 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x116cede v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x28ff43f5be1d 
Aborted (core dumped)`

**Comment by emma-borhanian** [comment]
Oh dear, `node --max-old-space-size=8192 arbital-scrape.js` fixes that but I've just pushed a [change](https://github.com/emma-borhanian/arbital-scrape/commit/f1f8ae1bc8fdd526b7070973a9109e2d413d60bf) to avoid downloading that zipfile altogether by default.

**Comment by shreyanshrs44** [comment]
`node arbital-scrape.js` works now !

**Comment by emma-borhanian** [comment]
Fixed in https://github.com/emma-borhanian/arbital-scrape/commit/77d43962515c610b9e1ce0c762a1a3306dcc072f
